final List<Map<String, dynamic>> mockFlights = [
  {
    'id': 'FL001',
    'airline': 'SkyConnect Airways',
    'airline_logo': 'assets/wallpaperflare.com_wallpaper (10).jpg',
    'flight_number': 'SC101',
    'departure_airport': 'Lagos (LOS)',
    'arrival_airport': 'Abuja (ABV)',
    'departure_time': DateTime(2025, 7, 6, 8, 0).toIso8601String(),
    'arrival_time': DateTime(2025, 7, 6, 10, 0).toIso8601String(),
    'price': 450.0,
    'aircraft': 'Boeing 737',
    'duration': 120,
    'stops': null,
    'travel_class': 'economy',
    'trip_type': 'oneWay',
  },
  {
    'id': 'FL002',
    'airline': 'Royal Wings',
    'airline_logo': 'assets/wallpaperflare.com_wallpaper (11).jpg',
    'flight_number': 'RW202',
    'departure_airport': 'Lagos (LOS)',
    'arrival_airport': 'London (LHR)',
    'departure_time': DateTime(2025, 7, 7, 22, 0).toIso8601String(),
    'arrival_time': DateTime(2025, 7, 8, 6, 30).toIso8601String(),
    'price': 1450.0,
    'aircraft': 'Airbus A350',
    'duration': 510,
    'stops': ['Paris'],
    'travel_class': 'business',
    'trip_type': 'roundTrip',
    'return_date': DateTime(2025, 7, 15, 16, 0).toIso8601String(),
  },
  {
    'id': 'FL003',
    'airline': 'Jet Africa',
    'airline_logo': 'assets/wallpaperflare.com_wallpaper (12).jpg',
    'flight_number': 'JA303',
    'departure_airport': 'Abuja (ABV)',
    'arrival_airport': 'Johannesburg (JNB)',
    'departure_time': DateTime(2025, 7, 9, 14, 0).toIso8601String(),
    'arrival_time': DateTime(2025, 7, 9, 20, 30).toIso8601String(),
    'price': 800.0,
    'aircraft': 'Boeing 777',
    'duration': 390,
    'stops': ['Nairobi'],
    'travel_class': 'premiumEconomy',
    'trip_type': 'oneWay',
  },
  {
    'id': 'FL004',
    'airline': 'Global Connect',
    'airline_logo': 'assets/wallpaperflare.com_wallpaper (13).jpg',
    'flight_number': 'GC404',
    'departure_airport': 'New York (JFK)',
    'arrival_airport': 'Lagos (LOS)',
    'departure_time': DateTime(2025, 7, 10, 6, 0).toIso8601String(),
    'arrival_time': DateTime(2025, 7, 10, 18, 30).toIso8601String(),
    'price': 2200.0,
    'aircraft': 'Airbus A380',
    'duration': 750,
    'stops': ['Frankfurt'],
    'travel_class': 'first',
    'trip_type': 'roundTrip',
    'return_date': DateTime(2025, 7, 20, 8, 0).toIso8601String(),
  },
  {
    'id': 'FL005',
    'airline': 'SkyConnect Airways',
    'airline_logo': 'assets/wallpaperflare.com_wallpaper (14).jpg',
    'flight_number': 'SC505',
    'departure_airport': 'Lagos (LOS)',
    'arrival_airport': 'Dubai (DXB)',
    'departure_time': DateTime(2025, 7, 8, 17, 0).toIso8601String(),
    'arrival_time': DateTime(2025, 7, 8, 23, 30).toIso8601String(),
    'price': 950.0,
    'aircraft': 'Boeing 787 Dreamliner',
    'duration': 390,
    'stops': null,
    'travel_class': 'economy',
    'trip_type': 'roundTrip',
    'return_date': DateTime(2025, 7, 16, 19, 0).toIso8601String(),
  },
  {
    'id': 'FL006',
    'airline': 'NovaAir',
    'airline_logo': 'assets/wallpaperflare.com_wallpaper (15).jpg',
    'flight_number': 'NA606',
    'departure_airport': 'Lagos (LOS)',
    'arrival_airport': 'Nairobi (NBO)',
    'departure_time': DateTime(2025, 7, 9, 10, 0).toIso8601String(),
    'arrival_time': DateTime(2025, 7, 9, 15, 0).toIso8601String(),
    'price': 740.0,
    'aircraft': 'Boeing 737 MAX',
    'duration': 300,
    'stops': ['Kigali'],
    'travel_class': 'economy',
    'trip_type': 'multiCity',
  },

  // Additional variations of the same flights with different travel classes and trip types

  // Lagos to Abuja variations
  {
    'id': 'FL001B',
    'airline': 'SkyConnect Airways',
    'airline_logo': 'assets/wallpaperflare.com_wallpaper (10).jpg',
    'flight_number': 'SC101',
    'departure_airport': 'Lagos (LOS)',
    'arrival_airport': 'Abuja (ABV)',
    'departure_time': DateTime(2025, 7, 6, 8, 0).toIso8601String(),
    'arrival_time': DateTime(2025, 7, 6, 10, 0).toIso8601String(),
    'price': 680.0,
    'aircraft': 'Boeing 737',
    'duration': 120,
    'stops': null,
    'travel_class': 'business',
    'trip_type': 'oneWay',
  },
  {
    'id': 'FL001C',
    'airline': 'SkyConnect Airways',
    'airline_logo': 'assets/wallpaperflare.com_wallpaper (10).jpg',
    'flight_number': 'SC101',
    'departure_airport': 'Lagos (LOS)',
    'arrival_airport': 'Abuja (ABV)',
    'departure_time': DateTime(2025, 7, 6, 8, 0).toIso8601String(),
    'arrival_time': DateTime(2025, 7, 6, 10, 0).toIso8601String(),
    'price': 850.0,
    'aircraft': 'Boeing 737',
    'duration': 120,
    'stops': null,
    'travel_class': 'economy',
    'trip_type': 'roundTrip',
    'return_date': DateTime(2025, 7, 13, 15, 0).toIso8601String(),
  },
  {
    'id': 'FL001D',
    'airline': 'SkyConnect Airways',
    'airline_logo': 'assets/wallpaperflare.com_wallpaper (10).jpg',
    'flight_number': 'SC101',
    'departure_airport': 'Lagos (LOS)',
    'arrival_airport': 'Abuja (ABV)',
    'departure_time': DateTime(2025, 7, 6, 8, 0).toIso8601String(),
    'arrival_time': DateTime(2025, 7, 6, 10, 0).toIso8601String(),
    'price': 580.0,
    'aircraft': 'Boeing 737',
    'duration': 120,
    'stops': null,
    'travel_class': 'premiumEconomy',
    'trip_type': 'oneWay',
  },

  // Lagos to London variations
  {
    'id': 'FL002B',
    'airline': 'Royal Wings',
    'airline_logo': 'assets/wallpaperflare.com_wallpaper (11).jpg',
    'flight_number': 'RW202',
    'departure_airport': 'Lagos (LOS)',
    'arrival_airport': 'London (LHR)',
    'departure_time': DateTime(2025, 7, 7, 22, 0).toIso8601String(),
    'arrival_time': DateTime(2025, 7, 8, 6, 30).toIso8601String(),
    'price': 850.0,
    'aircraft': 'Airbus A350',
    'duration': 510,
    'stops': ['Paris'],
    'travel_class': 'economy',
    'trip_type': 'oneWay',
  },
  {
    'id': 'FL002C',
    'airline': 'Royal Wings',
    'airline_logo': 'assets/wallpaperflare.com_wallpaper (11).jpg',
    'flight_number': 'RW202',
    'departure_airport': 'Lagos (LOS)',
    'arrival_airport': 'London (LHR)',
    'departure_time': DateTime(2025, 7, 7, 22, 0).toIso8601String(),
    'arrival_time': DateTime(2025, 7, 8, 6, 30).toIso8601String(),
    'price': 3200.0,
    'aircraft': 'Airbus A350',
    'duration': 510,
    'stops': ['Paris'],
    'travel_class': 'first',
    'trip_type': 'roundTrip',
    'return_date': DateTime(2025, 7, 15, 16, 0).toIso8601String(),
  },
  {
    'id': 'FL002D',
    'airline': 'Royal Wings',
    'airline_logo': 'assets/wallpaperflare.com_wallpaper (11).jpg',
    'flight_number': 'RW202',
    'departure_airport': 'Lagos (LOS)',
    'arrival_airport': 'London (LHR)',
    'departure_time': DateTime(2025, 7, 7, 22, 0).toIso8601String(),
    'arrival_time': DateTime(2025, 7, 8, 6, 30).toIso8601String(),
    'price': 1100.0,
    'aircraft': 'Airbus A350',
    'duration': 510,
    'stops': ['Paris'],
    'travel_class': 'premiumEconomy',
    'trip_type': 'oneWay',
  },

  // Abuja to Johannesburg variations
  {
    'id': 'FL003B',
    'airline': 'Jet Africa',
    'airline_logo': 'assets/wallpaperflare.com_wallpaper (12).jpg',
    'flight_number': 'JA303',
    'departure_airport': 'Abuja (ABV)',
    'arrival_airport': 'Johannesburg (JNB)',
    'departure_time': DateTime(2025, 7, 9, 14, 0).toIso8601String(),
    'arrival_time': DateTime(2025, 7, 9, 20, 30).toIso8601String(),
    'price': 620.0,
    'aircraft': 'Boeing 777',
    'duration': 390,
    'stops': ['Nairobi'],
    'travel_class': 'economy',
    'trip_type': 'oneWay',
  },
  {
    'id': 'FL003C',
    'airline': 'Jet Africa',
    'airline_logo': 'assets/wallpaperflare.com_wallpaper (12).jpg',
    'flight_number': 'JA303',
    'departure_airport': 'Abuja (ABV)',
    'arrival_airport': 'Johannesburg (JNB)',
    'departure_time': DateTime(2025, 7, 9, 14, 0).toIso8601String(),
    'arrival_time': DateTime(2025, 7, 9, 20, 30).toIso8601String(),
    'price': 1400.0,
    'aircraft': 'Boeing 777',
    'duration': 390,
    'stops': ['Nairobi'],
    'travel_class': 'business',
    'trip_type': 'roundTrip',
    'return_date': DateTime(2025, 7, 17, 12, 0).toIso8601String(),
  },
  {
    'id': 'FL003D',
    'airline': 'Jet Africa',
    'airline_logo': 'assets/wallpaperflare.com_wallpaper (12).jpg',
    'flight_number': 'JA303',
    'departure_airport': 'Abuja (ABV)',
    'arrival_airport': 'Johannesburg (JNB)',
    'departure_time': DateTime(2025, 7, 9, 14, 0).toIso8601String(),
    'arrival_time': DateTime(2025, 7, 9, 20, 30).toIso8601String(),
    'price': 920.0,
    'aircraft': 'Boeing 777',
    'duration': 390,
    'stops': ['Nairobi'],
    'travel_class': 'premiumEconomy',
    'trip_type': 'multiCity',
  },

  // New York to Lagos variations
  {
    'id': 'FL004B',
    'airline': 'Global Connect',
    'airline_logo': 'assets/wallpaperflare.com_wallpaper (13).jpg',
    'flight_number': 'GC404',
    'departure_airport': 'New York (JFK)',
    'arrival_airport': 'Lagos (LOS)',
    'departure_time': DateTime(2025, 7, 10, 6, 0).toIso8601String(),
    'arrival_time': DateTime(2025, 7, 10, 18, 30).toIso8601String(),
    'price': 1200.0,
    'aircraft': 'Airbus A380',
    'duration': 750,
    'stops': ['Frankfurt'],
    'travel_class': 'economy',
    'trip_type': 'oneWay',
  },
  {
    'id': 'FL004C',
    'airline': 'Global Connect',
    'airline_logo': 'assets/wallpaperflare.com_wallpaper (13).jpg',
    'flight_number': 'GC404',
    'departure_airport': 'New York (JFK)',
    'arrival_airport': 'Lagos (LOS)',
    'departure_time': DateTime(2025, 7, 10, 6, 0).toIso8601String(),
    'arrival_time': DateTime(2025, 7, 10, 18, 30).toIso8601String(),
    'price': 2800.0,
    'aircraft': 'Airbus A380',
    'duration': 750,
    'stops': ['Frankfurt'],
    'travel_class': 'business',
    'trip_type': 'roundTrip',
    'return_date': DateTime(2025, 7, 20, 8, 0).toIso8601String(),
  },
  {
    'id': 'FL004D',
    'airline': 'Global Connect',
    'airline_logo': 'assets/wallpaperflare.com_wallpaper (13).jpg',
    'flight_number': 'GC404',
    'departure_airport': 'New York (JFK)',
    'arrival_airport': 'Lagos (LOS)',
    'departure_time': DateTime(2025, 7, 10, 6, 0).toIso8601String(),
    'arrival_time': DateTime(2025, 7, 10, 18, 30).toIso8601String(),
    'price': 1650.0,
    'aircraft': 'Airbus A380',
    'duration': 750,
    'stops': ['Frankfurt'],
    'travel_class': 'premiumEconomy',
    'trip_type': 'oneWay',
  },

  // Lagos to Dubai variations
  {
    'id': 'FL005B',
    'airline': 'SkyConnect Airways',
    'airline_logo': 'assets/wallpaperflare.com_wallpaper (14).jpg',
    'flight_number': 'SC505',
    'departure_airport': 'Lagos (LOS)',
    'arrival_airport': 'Dubai (DXB)',
    'departure_time': DateTime(2025, 7, 8, 17, 0).toIso8601String(),
    'arrival_time': DateTime(2025, 7, 8, 23, 30).toIso8601String(),
    'price': 750.0,
    'aircraft': 'Boeing 787 Dreamliner',
    'duration': 390,
    'stops': null,
    'travel_class': 'economy',
    'trip_type': 'oneWay',
  },
  {
    'id': 'FL005C',
    'airline': 'SkyConnect Airways',
    'airline_logo': 'assets/wallpaperflare.com_wallpaper (14).jpg',
    'flight_number': 'SC505',
    'departure_airport': 'Lagos (LOS)',
    'arrival_airport': 'Dubai (DXB)',
    'departure_time': DateTime(2025, 7, 8, 17, 0).toIso8601String(),
    'arrival_time': DateTime(2025, 7, 8, 23, 30).toIso8601String(),
    'price': 2200.0,
    'aircraft': 'Boeing 787 Dreamliner',
    'duration': 390,
    'stops': null,
    'travel_class': 'business',
    'trip_type': 'roundTrip',
    'return_date': DateTime(2025, 7, 16, 19, 0).toIso8601String(),
  },
  {
    'id': 'FL005D',
    'airline': 'SkyConnect Airways',
    'airline_logo': 'assets/wallpaperflare.com_wallpaper (14).jpg',
    'flight_number': 'SC505',
    'departure_airport': 'Lagos (LOS)',
    'arrival_airport': 'Dubai (DXB)',
    'departure_time': DateTime(2025, 7, 8, 17, 0).toIso8601String(),
    'arrival_time': DateTime(2025, 7, 8, 23, 30).toIso8601String(),
    'price': 3500.0,
    'aircraft': 'Boeing 787 Dreamliner',
    'duration': 390,
    'stops': null,
    'travel_class': 'first',
    'trip_type': 'roundTrip',
    'return_date': DateTime(2025, 7, 16, 19, 0).toIso8601String(),
  },

  // Lagos to Nairobi variations
  {
    'id': 'FL006B',
    'airline': 'NovaAir',
    'airline_logo': 'assets/wallpaperflare.com_wallpaper (15).jpg',
    'flight_number': 'NA606',
    'departure_airport': 'Lagos (LOS)',
    'arrival_airport': 'Nairobi (NBO)',
    'departure_time': DateTime(2025, 7, 9, 10, 0).toIso8601String(),
    'arrival_time': DateTime(2025, 7, 9, 15, 0).toIso8601String(),
    'price': 1350.0,
    'aircraft': 'Boeing 737 MAX',
    'duration': 300,
    'stops': ['Kigali'],
    'travel_class': 'business',
    'trip_type': 'roundTrip',
    'return_date': DateTime(2025, 7, 18, 11, 0).toIso8601String(),
  },
  {
    'id': 'FL006C',
    'airline': 'NovaAir',
    'airline_logo': 'assets/wallpaperflare.com_wallpaper (15).jpg',
    'flight_number': 'NA606',
    'departure_airport': 'Lagos (LOS)',
    'arrival_airport': 'Nairobi (NBO)',
    'departure_time': DateTime(2025, 7, 9, 10, 0).toIso8601String(),
    'arrival_time': DateTime(2025, 7, 9, 15, 0).toIso8601String(),
    'price': 620.0,
    'aircraft': 'Boeing 737 MAX',
    'duration': 300,
    'stops': ['Kigali'],
    'travel_class': 'economy',
    'trip_type': 'oneWay',
  },
  {
    'id': 'FL006D',
    'airline': 'NovaAir',
    'airline_logo': 'assets/wallpaperflare.com_wallpaper (15).jpg',
    'flight_number': 'NA606',
    'departure_airport': 'Lagos (LOS)',
    'arrival_airport': 'Nairobi (NBO)',
    'departure_time': DateTime(2025, 7, 9, 10, 0).toIso8601String(),
    'arrival_time': DateTime(2025, 7, 9, 15, 0).toIso8601String(),
    'price': 920.0,
    'aircraft': 'Boeing 737 MAX',
    'duration': 300,
    'stops': ['Kigali'],
    'travel_class': 'premiumEconomy',
    'trip_type': 'roundTrip',
    'return_date': DateTime(2025, 7, 18, 11, 0).toIso8601String(),
  },

  // Additional stops variations for existing routes

  // Lagos to London with different stops
  {
    'id': 'FL002E',
    'airline': 'Royal Wings',
    'airline_logo': 'assets/wallpaperflare.com_wallpaper (11).jpg',
    'flight_number': 'RW203',
    'departure_airport': 'Lagos (LOS)',
    'arrival_airport': 'London (LHR)',
    'departure_time': DateTime(2025, 7, 7, 20, 0).toIso8601String(),
    'arrival_time': DateTime(2025, 7, 8, 8, 45).toIso8601String(),
    'price': 950.0,
    'aircraft': 'Airbus A350',
    'duration': 585,
    'stops': ['Amsterdam'],
    'travel_class': 'economy',
    'trip_type': 'oneWay',
  },
  {
    'id': 'FL002F',
    'airline': 'Royal Wings',
    'airline_logo': 'assets/wallpaperflare.com_wallpaper (11).jpg',
    'flight_number': 'RW204',
    'departure_airport': 'Lagos (LOS)',
    'arrival_airport': 'London (LHR)',
    'departure_time': DateTime(2025, 7, 7, 18, 30).toIso8601String(),
    'arrival_time': DateTime(2025, 7, 8, 9, 15).toIso8601String(),
    'price': 820.0,
    'aircraft': 'Airbus A350',
    'duration': 645,
    'stops': ['Istanbul', 'Rome'],
    'travel_class': 'economy',
    'trip_type': 'oneWay',
  },
  {
    'id': 'FL002G',
    'airline': 'Royal Wings',
    'airline_logo': 'assets/wallpaperflare.com_wallpaper (11).jpg',
    'flight_number': 'RW205',
    'departure_airport': 'Lagos (LOS)',
    'arrival_airport': 'London (LHR)',
    'departure_time': DateTime(2025, 7, 7, 21, 0).toIso8601String(),
    'arrival_time': DateTime(2025, 7, 8, 5, 30).toIso8601String(),
    'price': 1100.0,
    'aircraft': 'Airbus A350',
    'duration': 450,
    'stops': null,
    'travel_class': 'economy',
    'trip_type': 'oneWay',
  },

  // New York to Lagos with different stops
  {
    'id': 'FL004E',
    'airline': 'Global Connect',
    'airline_logo': 'assets/wallpaperflare.com_wallpaper (13).jpg',
    'flight_number': 'GC405',
    'departure_airport': 'New York (JFK)',
    'arrival_airport': 'Lagos (LOS)',
    'departure_time': DateTime(2025, 7, 10, 8, 0).toIso8601String(),
    'arrival_time': DateTime(2025, 7, 10, 22, 30).toIso8601String(),
    'price': 1350.0,
    'aircraft': 'Airbus A380',
    'duration': 810,
    'stops': ['London'],
    'travel_class': 'economy',
    'trip_type': 'oneWay',
  },
  {
    'id': 'FL004F',
    'airline': 'Global Connect',
    'airline_logo': 'assets/wallpaperflare.com_wallpaper (13).jpg',
    'flight_number': 'GC406',
    'departure_airport': 'New York (JFK)',
    'arrival_airport': 'Lagos (LOS)',
    'departure_time': DateTime(2025, 7, 10, 5, 0).toIso8601String(),
    'arrival_time': DateTime(2025, 7, 11, 1, 45).toIso8601String(),
    'price': 1180.0,
    'aircraft': 'Airbus A380',
    'duration': 885,
    'stops': ['Paris', 'Casablanca'],
    'travel_class': 'economy',
    'trip_type': 'oneWay',
  },
  {
    'id': 'FL004G',
    'airline': 'Global Connect',
    'airline_logo': 'assets/wallpaperflare.com_wallpaper (13).jpg',
    'flight_number': 'GC407',
    'departure_airport': 'New York (JFK)',
    'arrival_airport': 'Lagos (LOS)',
    'departure_time': DateTime(2025, 7, 10, 7, 30).toIso8601String(),
    'arrival_time': DateTime(2025, 7, 10, 17, 0).toIso8601String(),
    'price': 1450.0,
    'aircraft': 'Airbus A380',
    'duration': 690,
    'stops': null,
    'travel_class': 'economy',
    'trip_type': 'oneWay',
  },

  // Abuja to Johannesburg with different stops
  {
    'id': 'FL003E',
    'airline': 'Jet Africa',
    'airline_logo': 'assets/wallpaperflare.com_wallpaper (12).jpg',
    'flight_number': 'JA304',
    'departure_airport': 'Abuja (ABV)',
    'arrival_airport': 'Johannesburg (JNB)',
    'departure_time': DateTime(2025, 7, 9, 12, 0).toIso8601String(),
    'arrival_time': DateTime(2025, 7, 9, 19, 30).toIso8601String(),
    'price': 680.0,
    'aircraft': 'Boeing 777',
    'duration': 450,
    'stops': ['Addis Ababa'],
    'travel_class': 'economy',
    'trip_type': 'oneWay',
  },
  {
    'id': 'FL003F',
    'airline': 'Jet Africa',
    'airline_logo': 'assets/wallpaperflare.com_wallpaper (12).jpg',
    'flight_number': 'JA305',
    'departure_airport': 'Abuja (ABV)',
    'arrival_airport': 'Johannesburg (JNB)',
    'departure_time': DateTime(2025, 7, 9, 11, 0).toIso8601String(),
    'arrival_time': DateTime(2025, 7, 9, 21, 15).toIso8601String(),
    'price': 750.0,
    'aircraft': 'Boeing 777',
    'duration': 495,
    'stops': ['Cairo', 'Nairobi'],
    'travel_class': 'economy',
    'trip_type': 'oneWay',
  },
  {
    'id': 'FL003G',
    'airline': 'Jet Africa',
    'airline_logo': 'assets/wallpaperflare.com_wallpaper (12).jpg',
    'flight_number': 'JA306',
    'departure_airport': 'Abuja (ABV)',
    'arrival_airport': 'Johannesburg (JNB)',
    'departure_time': DateTime(2025, 7, 9, 16, 0).toIso8601String(),
    'arrival_time': DateTime(2025, 7, 9, 22, 30).toIso8601String(),
    'price': 920.0,
    'aircraft': 'Boeing 777',
    'duration': 330,
    'stops': null,
    'travel_class': 'economy',
    'trip_type': 'oneWay',
  },

  // Lagos to Dubai with different stops
  {
    'id': 'FL005E',
    'airline': 'SkyConnect Airways',
    'airline_logo': 'assets/wallpaperflare.com_wallpaper (14).jpg',
    'flight_number': 'SC506',
    'departure_airport': 'Lagos (LOS)',
    'arrival_airport': 'Dubai (DXB)',
    'departure_time': DateTime(2025, 7, 8, 15, 0).toIso8601String(),
    'arrival_time': DateTime(2025, 7, 9, 0, 45).toIso8601String(),
    'price': 820.0,
    'aircraft': 'Boeing 787 Dreamliner',
    'duration': 465,
    'stops': ['Cairo'],
    'travel_class': 'economy',
    'trip_type': 'oneWay',
  },
  {
    'id': 'FL005F',
    'airline': 'SkyConnect Airways',
    'airline_logo': 'assets/wallpaperflare.com_wallpaper (14).jpg',
    'flight_number': 'SC507',
    'departure_airport': 'Lagos (LOS)',
    'arrival_airport': 'Dubai (DXB)',
    'departure_time': DateTime(2025, 7, 8, 14, 30).toIso8601String(),
    'arrival_time': DateTime(2025, 7, 9, 2, 15).toIso8601String(),
    'price': 780.0,
    'aircraft': 'Boeing 787 Dreamliner',
    'duration': 525,
    'stops': ['Istanbul', 'Doha'],
    'travel_class': 'economy',
    'trip_type': 'oneWay',
  },

  // Lagos to Nairobi with different stops
  {
    'id': 'FL006E',
    'airline': 'NovaAir',
    'airline_logo': 'assets/wallpaperflare.com_wallpaper (15).jpg',
    'flight_number': 'NA607',
    'departure_airport': 'Lagos (LOS)',
    'arrival_airport': 'Nairobi (NBO)',
    'departure_time': DateTime(2025, 7, 9, 9, 0).toIso8601String(),
    'arrival_time': DateTime(2025, 7, 9, 16, 30).toIso8601String(),
    'price': 680.0,
    'aircraft': 'Boeing 737 MAX',
    'duration': 330,
    'stops': ['Addis Ababa'],
    'travel_class': 'economy',
    'trip_type': 'oneWay',
  },
  {
    'id': 'FL006F',
    'airline': 'NovaAir',
    'airline_logo': 'assets/wallpaperflare.com_wallpaper (15).jpg',
    'flight_number': 'NA608',
    'departure_airport': 'Lagos (LOS)',
    'arrival_airport': 'Nairobi (NBO)',
    'departure_time': DateTime(2025, 7, 9, 11, 30).toIso8601String(),
    'arrival_time': DateTime(2025, 7, 9, 14, 0).toIso8601String(),
    'price': 850.0,
    'aircraft': 'Boeing 737 MAX',
    'duration': 270,
    'stops': null,
    'travel_class': 'economy',
    'trip_type': 'oneWay',
  },
  {
    'id': 'FL006G',
    'airline': 'NovaAir',
    'airline_logo': 'assets/wallpaperflare.com_wallpaper (15).jpg',
    'flight_number': 'NA609',
    'departure_airport': 'Lagos (LOS)',
    'arrival_airport': 'Nairobi (NBO)',
    'departure_time': DateTime(2025, 7, 9, 8, 0).toIso8601String(),
    'arrival_time': DateTime(2025, 7, 9, 17, 45).toIso8601String(),
    'price': 640.0,
    'aircraft': 'Boeing 737 MAX',
    'duration': 405,
    'stops': ['N\'Djamena', 'Khartoum'],
    'travel_class': 'economy',
    'trip_type': 'oneWay',
  },

  // Lagos to Abuja with different stops variations
  {
    'id': 'FL001E',
    'airline': 'SkyConnect Airways',
    'airline_logo': 'assets/wallpaperflare.com_wallpaper (10).jpg',
    'flight_number': 'SC102',
    'departure_airport': 'Lagos (LOS)',
    'arrival_airport': 'Abuja (ABV)',
    'departure_time': DateTime(2025, 7, 6, 12, 0).toIso8601String(),
    'arrival_time': DateTime(2025, 7, 6, 15, 30).toIso8601String(),
    'price': 380.0,
    'aircraft': 'Boeing 737',
    'duration': 180,
    'stops': ['Ibadan'],
    'travel_class': 'economy',
    'trip_type': 'oneWay',
  },
  {
    'id': 'FL001F',
    'airline': 'SkyConnect Airways',
    'airline_logo': 'assets/wallpaperflare.com_wallpaper (10).jpg',
    'flight_number': 'SC103',
    'departure_airport': 'Lagos (LOS)',
    'arrival_airport': 'Abuja (ABV)',
    'departure_time': DateTime(2025, 7, 6, 14, 0).toIso8601String(),
    'arrival_time': DateTime(2025, 7, 6, 18, 45).toIso8601String(),
    'price': 320.0,
    'aircraft': 'Boeing 737',
    'duration': 225,
    'stops': ['Jos', 'Kaduna'],
    'travel_class': 'economy',
    'trip_type': 'oneWay',
  },

  // Additional completely new routes for variety
  {
    'id': 'FL007',
    'airline': 'Atlantic Airways',
    'airline_logo': 'assets/wallpaperflare.com_wallpaper (16).jpg',
    'flight_number': 'AA701',
    'departure_airport': 'Lagos (LOS)',
    'arrival_airport': 'Accra (ACC)',
    'departure_time': DateTime(2025, 7, 11, 9, 0).toIso8601String(),
    'arrival_time': DateTime(2025, 7, 11, 10, 30).toIso8601String(),
    'price': 280.0,
    'aircraft': 'Airbus A320',
    'duration': 90,
    'stops': null,
    'travel_class': 'economy',
    'trip_type': 'oneWay',
  },
  {
    'id': 'FL007B',
    'airline': 'Atlantic Airways',
    'airline_logo': 'assets/wallpaperflare.com_wallpaper (16).jpg',
    'flight_number': 'AA702',
    'departure_airport': 'Lagos (LOS)',
    'arrival_airport': 'Accra (ACC)',
    'departure_time': DateTime(2025, 7, 11, 11, 0).toIso8601String(),
    'arrival_time': DateTime(2025, 7, 11, 13, 15).toIso8601String(),
    'price': 240.0,
    'aircraft': 'Airbus A320',
    'duration': 135,
    'stops': ['Cotonou'],
    'travel_class': 'economy',
    'trip_type': 'oneWay',
  },

  // Lagos to Cape Town with various stops
  {
    'id': 'FL008',
    'airline': 'AfriSky',
    'airline_logo': 'assets/wallpaperflare.com_wallpaper (17).jpg',
    'flight_number': 'AS801',
    'departure_airport': 'Lagos (LOS)',
    'arrival_airport': 'Cape Town (CPT)',
    'departure_time': DateTime(2025, 7, 12, 6, 0).toIso8601String(),
    'arrival_time': DateTime(2025, 7, 12, 18, 30).toIso8601String(),
    'price': 1100.0,
    'aircraft': 'Boeing 777',
    'duration': 630,
    'stops': ['Johannesburg'],
    'travel_class': 'economy',
    'trip_type': 'oneWay',
  },
  {
    'id': 'FL008B',
    'airline': 'AfriSky',
    'airline_logo': 'assets/wallpaperflare.com_wallpaper (17).jpg',
    'flight_number': 'AS802',
    'departure_airport': 'Lagos (LOS)',
    'arrival_airport': 'Cape Town (CPT)',
    'departure_time': DateTime(2025, 7, 12, 8, 0).toIso8601String(),
    'arrival_time': DateTime(2025, 7, 12, 22, 45).toIso8601String(),
    'price': 980.0,
    'aircraft': 'Boeing 777',
    'duration': 705,
    'stops': ['Luanda', 'Windhoek'],
    'travel_class': 'economy',
    'trip_type': 'oneWay',
  },
  {
    'id': 'FL008C',
    'airline': 'AfriSky',
    'airline_logo': 'assets/wallpaperflare.com_wallpaper (17).jpg',
    'flight_number': 'AS803',
    'departure_airport': 'Lagos (LOS)',
    'arrival_airport': 'Cape Town (CPT)',
    'departure_time': DateTime(2025, 7, 12, 10, 0).toIso8601String(),
    'arrival_time': DateTime(2025, 7, 12, 16, 30).toIso8601String(),
    'price': 1350.0,
    'aircraft': 'Boeing 777',
    'duration': 510,
    'stops': null,
    'travel_class': 'economy',
    'trip_type': 'oneWay',
  },

  // Abuja to Cairo with different stops
  {
    'id': 'FL009',
    'airline': 'Desert Wings',
    'airline_logo': 'assets/wallpaperflare.com_wallpaper (18).jpg',
    'flight_number': 'DW901',
    'departure_airport': 'Abuja (ABV)',
    'arrival_airport': 'Cairo (CAI)',
    'departure_time': DateTime(2025, 7, 13, 15, 0).toIso8601String(),
    'arrival_time': DateTime(2025, 7, 13, 21, 30).toIso8601String(),
    'price': 720.0,
    'aircraft': 'Airbus A330',
    'duration': 390,
    'stops': null,
    'travel_class': 'economy',
    'trip_type': 'oneWay',
  },
  {
    'id': 'FL009B',
    'airline': 'Desert Wings',
    'airline_logo': 'assets/wallpaperflare.com_wallpaper (18).jpg',
    'flight_number': 'DW902',
    'departure_airport': 'Abuja (ABV)',
    'arrival_airport': 'Cairo (CAI)',
    'departure_time': DateTime(2025, 7, 13, 13, 0).toIso8601String(),
    'arrival_time': DateTime(2025, 7, 14, 0, 15).toIso8601String(),
    'price': 650.0,
    'aircraft': 'Airbus A330',
    'duration': 495,
    'stops': ['Khartoum'],
    'travel_class': 'economy',
    'trip_type': 'oneWay',
  },
  {
    'id': 'FL009C',
    'airline': 'Desert Wings',
    'airline_logo': 'assets/wallpaperflare.com_wallpaper (18).jpg',
    'flight_number': 'DW903',
    'departure_airport': 'Abuja (ABV)',
    'arrival_airport': 'Cairo (CAI)',
    'departure_time': DateTime(2025, 7, 13, 11, 30).toIso8601String(),
    'arrival_time': DateTime(2025, 7, 14, 1, 45).toIso8601String(),
    'price': 580.0,
    'aircraft': 'Airbus A330',
    'duration': 555,
    'stops': ['N\'Djamena', 'Tripoli'],
    'travel_class': 'economy',
    'trip_type': 'oneWay',
  },
];
